[package]
name = "pdf_viewer"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/pdf_viewer.rs"
doctest = false

[dependencies]
anyhow.workspace = true
image.workspace = true
log.workspace = true
parking_lot.workspace = true
pdfium-render.workspace = true
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
